---
# tasks file for Director
 - name: Installing the Director Packages
   command: yum install -y python-tripleoclient

 - name: Configuring the Director
   command: cp /usr/share/instack-undercloud/undercloud.conf.sample ~/undercloud.conf

 - name: Configuring undercloud.conf
   lineinfile: path=/home/stack/undercloud.conf regexp={{ item.regexp }} line={{ item.line}} state=present
   with_items:
    - { regexp: "^undercloud_hostname" ,line: "undercloud_hostname=ucloud.jiolabs.com" }
    - { regexp: "^local_ip" , line: "local_ip=10.64.105.66/27" }
    - { regexp: "^network_gateway", line: "network_gateway=10.64.105.66" }
    - { regexp: "^undercloud_public_vip", line: "undercloud_public_vip=10.64.105.67" }
    - { regexp: "^undercloud_admin_vip", line: "undercloud_admin_vip=10.64.105.68" }
    - { regexp: "^local_interface", line: "local_interface=eno1" }
    - { regexp: "^network_cidr", line: "network_cidr=10.64.105.64/27" }
    - { regexp: "^dhcp_start", line: "dhcp_start=10.64.105.69" }
    - { regexp: "^dhcp_end", line: "dhcp_end=10.64.105.85" }
    - { regexp: "^inspection_interface", line: "inspection_interface=br-ctlplane" }
    - { regexp: "^inspection_iprange", line: "inspection_iprange=10.64.105.86,10.64.105.94" }
    - { regexp: "^undercloud_debug ", line: "undercloud_debug=true" }
    - { regexp: "^enable_tempest ", line: "enable_tempest=true" }
    - { regexp: "^enable_mistral ", line: "enable_mistral=true" }
    - { regexp: "^enable_zaqar ", line: "enable_zaqar=true" }
    - { regexp: "^enable_telemetry", line: "enable_telemetry=true" }
    - { regexp: "^enable_ui ", line: "enable_ui=true" }
    - { regexp: "^enable_validations", line: "enable_validations=true" }
    - { regexp: "^ipxe_enabled", line: "ipxe_enabled=true" }
    - { regexp: "^store_events", line: "store_events=true" }
    - { regexp: "^undercloud_db_password", line: "undercloud_db_password=reliance123" }
    - { regexp: "^undercloud_admin_password", line: "undercloud_admin_password=reliance123" }
    - { regexp: "^undercloud_glance_password", line: "undercloud_glance_password=reliance123" }
    - { regexp: "^undercloud_heat_password", line: "undercloud_heat_password=reliance123" }
    - { regexp: "^undercloud_neutron_password", line: "undercloud_neutron_password=reliance123" }
    - { regexp: "^undercloud_nova_password", line: "undercloud_nova_password=reliance123" }
    - { regexp: "^undercloud_ironic_password", line: "undercloud_ironic_password=reliance123" }
    - { regexp: "^undercloud_aodh_password", line: "undercloud_aodh_password=reliance123" }
    - { regexp: "^undercloud_ceilometer_password", line: "undercloud_ceilometer_password=reliance123" }
    - { regexp: "^undercloud_ceilometer_snmpd_password", line: "undercloud_ceilometer_snmpd_password=reliance123" }
    - { regexp: "^undercloud_swift_password", line: "undercloud_swift_password=reliance123" }
    - { regexp: "^undercloud_mistral_password", line: "undercloud_mistral_password=reliance123" }
    - { regexp: "^undercloud_rabbit_password", line: "undercloud_rabbit_password=reliance123" }
    - { regexp: "^undercloud_heat_stack_domain_admin_password", line: "undercloud_heat_stack_domain_admin_password=reliance123" }
    - { regexp: "^undercloud_sensu_password", line: "undercloud_sensu_password=reliance123" }
    - { regexp: "^undercloud_haproxy_stats_password", line: "undercloud_haproxy_stats_password=reliance123" }
    - { regexp: "^undercloud_zaqar_password", line: "undercloud_zaqar_password=reliance123" }
 
 
 - name: Install UnderCloud Finally 
   command: openstack undercloud install
 
 
 
